CREATE TABLE tblBKR_Class (
    Contract VARCHAR(16),
    Kredietnemernaam VARCHAR(24),
    Voorletters VARCHAR(5),
    Prefix VARCHAR(8),
    Geboortedatum DATE,
    Straat VARCHAR(24),
    Huisnummer VARCHAR(5),
    Alfanumeriek1 VARCHAR(5),
    Postcode VARCHAR(4),
    Alfanumeriek2 VARCHAR(2),
    Woonplaats VARCHAR(24),
    Contractnummer VARCHAR(16),
    Contractsoort VARCHAR(2),
    Deelnemernummer VARCHAR(7),
    Registratiedatum DATE,
    DatumLaatsteMutatie DATE,
    LimietContractBedrag DECIMAL(8, 0),
    Opnamebedrag DECIMAL(8, 0),
    DatumEersteAflossing DATE,
    DatumTLaatsteAflossing DATE,
    DatumPLaatsteAflossing DATE,
    IndicatieBKRAfgelost VARCHAR(1),
    AchterstCode1 VARCHAR(1),
    DatumAchterstCode1 DATE,
    AchterstCode2 VARCHAR(1),
    DatumAchterstCode2 DATE,
    AchterstCode3 VARCHAR(1),
    DatumAchterstCode3 DATE,
    AchterstCode4 VARCHAR(1),
    DatumAchterstCode4 DATE,
    AchterstCode5 VARCHAR(1),
    DatumAchterstCode5 DATE,
    AchterstCode6 VARCHAR(1),
    DatumAchterstCode6 DATE,
    AchterstCode7 VARCHAR(1),
    DatumAchterstCode7 DATE,
    Geslacht VARCHAR(6),
    LandCode VARCHAR(3)
);

CREATE TABLE tblCustomer (
    Customer VARCHAR(16),
    Kredietnemernaam VARCHAR(24),
    Voorletters VARCHAR(5),
    Prefix VARCHAR(8),
    Geboortedatum DATE,
    Straat VARCHAR(24),
    Huisnummer VARCHAR(5),
    Alfanumeriek1 VARCHAR(5),
    Postcode VARCHAR(4),
    Alfanumeriek2 VARCHAR(2),
    Woonplaats VARCHAR(24),
    Geslacht VARCHAR(6),
    LandCode VARCHAR(3)
);


CREATE TABLE tblContract (
	Customer1 VARCHAR(16),
	Customer2 VARCHAR(16),
    Contractnummer VARCHAR(16),
    Contractsoort VARCHAR(2),
    Deelnemernummer VARCHAR(7),
    Registratiedatum DATE,
    LimietContractBedrag DECIMAL(8, 0),
    Opnamebedrag DECIMAL(8, 0),
    DatumEersteAflossing DATE,
    DatumTLaatsteAflossing DATE,
    DatumPLaatsteAflossing DATE,
    IndicatieBKRAfgelost VARCHAR(1),
	NumberOfPaymentsMissed DECIMAL(4,0)
);

